# This workflow will install Python dependencies, run tests, lint, and publish to GitHub Packages

name: Python package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest build twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Build package
      run: |
        python -m pip install --upgrade pip
        python -m pip install build twine
        python -m build
    - name: Publish to GitHub Packages
      env:
        TWINE_USERNAME: ${{ github.actor }}
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        #python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        # For GitHub Packages use:
        # python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        # To publish to GitHub Packages, use the following URL:
        # python -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
        # But for GitHub Packages (not PyPI), use:
        python -m twine upload --repository-url https://upload.github.com/michael-brux/sshost dist/*


